name       : incidenceeditor
version    : 22.04.2
release    : 64
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/incidenceeditor-22.04.2.tar.xz : 4ae8c21c11bacfac8d9f92ade718ee4cdc51c602c66b024e2f4c6a2fc3ccb07c
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM incidence editor
description: |
    KDE PIM incidence editor.
builddeps  :
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - calendarsupport-devel
    - eventviews-devel
    - kcontacts-devel
    - kdiagram-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kio-devel
    - kldap-devel
    - kmailtransport-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
