name       : incidenceeditor
version    : 20.12.3
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/incidenceeditor-20.12.3.tar.xz : 44059c06fc725b085a196c619cdb509829f7a57f17eced56fc6755cdcd07ce13
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM incidence editor
description: |
    KDE PIM incidence editor.
builddeps  :
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - calendarsupport-devel
    - eventviews-devel
    - kcontacts-devel
    - kdiagram-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kio-devel
    - kldap-devel
    - kmailtransport-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
