name       : incidenceeditor
version    : 23.04.2
release    : 70
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/incidenceeditor-23.04.2.tar.xz : b303bfafc5c470c34aecebe12c282653d459d4bf7c9e23c122ac51983f67a2cd
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM incidence editor
description: |
    KDE PIM incidence editor.
builddeps  :
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - calendarsupport-devel
    - eventviews-devel
    - kcontacts-devel
    - kdiagram-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kio-devel
    - kldap-devel
    - kmailtransport-devel
    - ktextaddons-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
