name       : incidenceeditor
version    : 19.04.2
release    : 23
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.2/src/incidenceeditor-19.04.2.tar.xz : 2a53c4cfd0a77b0f579a581143288bedffc91257fb13c2192bc10d0d1f572814
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM incidence editor
description: |
    KDE PIM incidence editor.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libsasl2)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - calendarsupport-devel
    - eventviews-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcompletion-devel
    - kcodecs-devel
    - kcontacts-devel
    - kdepim-apps-libs-devel
    - kdesignerplugin-devel
    - kdiagram-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kio-devel
    - kitemmodels-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
