name       : incidenceeditor
version    : 19.08.1
release    : 27
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/incidenceeditor-19.08.1.tar.xz : 591781da9b3bc4b0f366ffa8de658aa31f48e1f435a434669b7c11b5f3a55403
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM incidence editor
description: |
    KDE PIM incidence editor.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libsasl2)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - calendarsupport-devel
    - eventviews-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdepim-apps-libs-devel
    - kdesignerplugin-devel
    - kdiagram-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kio-devel
    - kitemmodels-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
