name       : incidenceeditor
version    : 18.12.2
release    : 18
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/incidenceeditor-18.12.2.tar.xz : 7526488ff3ddcdd24eb4651f1aecca89675c04696d7e236acb876e67a4eb89a6
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM incidence editor
description: |
    KDE PIM incidence editor.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libsasl2)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - calendarsupport-devel
    - eventviews-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcompletion-devel
    - kcodecs-devel
    - kcontacts-devel
    - kdepim-apps-libs-devel
    - kdesignerplugin-devel
    - kdiagram-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kio-devel
    - kitemmodels-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
