name       : incidenceeditor
version    : 17.04.1
release    : 1
source     :
    - https://download.kde.org/stable/applications/17.04.1/src/incidenceeditor-17.04.1.tar.xz : 8df15c6cbc9defd7c99ed06f04ecc95547df3208ce31ba31a3f24acba1c71356
license    : 
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : KDE PIM incidence editor.
description: |
    KDE PIM incidence editor.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Core)
    - pkgconfig(libsasl2)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - calendarsupport-devel
    - eventviews-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdelibs4support-devel
    - kdepim-apps-libs-devel
    - kdesignerplugin-devel
    - kdiagram-devel
    - kdoctools-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - openldap-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
