name       : incidenceeditor
version    : 18.08.2
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/incidenceeditor-18.08.2.tar.xz : 78a4197a2a5bc14d1dd816197f4d19a74103a92ecb9220cb5d90757212b75524
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : KDE PIM incidence editor
description: |
    KDE PIM incidence editor.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libsasl2)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - calendarsupport-devel
    - eventviews-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcompletion-devel
    - kcodecs-devel
    - kcontacts-devel
    - kdepim-apps-libs-devel
    - kdesignerplugin-devel
    - kdiagram-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kio-devel
    - kitemmodels-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
