name       : incidenceeditor
version    : 20.12.1
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/incidenceeditor-20.12.1.tar.xz : 4ce16a4dbbf17a6427e2493968a4dc7ab3a1c85204f6fb38947d2b1d75f0bec1
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM incidence editor
description: |
    KDE PIM incidence editor.
builddeps  :
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - calendarsupport-devel
    - eventviews-devel
    - kcontacts-devel
    - kdiagram-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kio-devel
    - kldap-devel
    - kmailtransport-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
