name       : incidenceeditor
version    : 21.12.0
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/incidenceeditor-21.12.0.tar.xz : 57df77be28e81f5b1b15cd1e65dc5b7f549f32e5e4c0be37768f0000c5502de7
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM incidence editor
description: |
    KDE PIM incidence editor.
builddeps  :
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - calendarsupport-devel
    - eventviews-devel
    - kcontacts-devel
    - kdiagram-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kio-devel
    - kldap-devel
    - kmailtransport-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
